# Cosa bisogna fare?
# -- FATTO get /users
# -- FATTO post
# -- FATTO get /users/{id}
# -- FATTO put: update dei dati
# -- FATTO delete: eliminazione utente
# -- FATTO get /events
# -- FATTO post
# -- FATTO get /events/{id}
# put
# delete
# -- FATTO get /zone
# -- FATTO get /zones/{id}
# get /cameras
# get /cameras/{id}

# TODO:
# - Da capire se lasciare le coordinate nell'evento o se mantenere solo le zone

# Per le resources usare lo schema definito sotto (con $ref:, vedi linea 45 per esempio)
# I dati di esempio son da definire nella parte components

openapi: 3.0.0
info:
  title: UrbanFlow API
  description: Docs ufficiali per le API utilizzati nel progetto UrbanFlow.
  version: 0.0.1
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
tags:
  - name: User
    description: Endpoints relativi a un oggetto utente.
  - name: Event
    description: Endpoints relativi a un oggetto evento.
  - name: Zone
    description: Endpoints relativi a un oggetto zona.

# per i JWT come facciamo? ALV: Boh non so cosa siano
paths:
  /users:
    get:
      tags:
        - User
      summary: Restituisce la lista degli utenti.
      description: Restituisce la lista degli utenti presenti sulla piattaforma.
      parameters:
        - name: role
          in: query
          required: false
          description: Ruolo degli utenti da cercare, se non specificato restituisce tutti gli utenti.
          schema:
            type: string
            enum:
              - admin
              - base
      responses:
        200: # success
          description: Risorsa JSON contenente lista degli utenti.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/user"
        400: # bad request
          description: Richiesta non valida.
        401: #unauthorized
          description: Accesso non autorizzato alla risorsa.
    post:
      tags:
        - User
      summary: Crea un nuovo utente.
      description: Aggiunge un nuovo utente al database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user"
      responses:
        201: # resp: utente creato
          description: Utente creato.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        400: # bad request
          description: Richiesta non valida.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Descrizione dell'errore.
                    example: Il campo 'name' è richiesto.
        401: # unauthorized
          description: Accesso non autorizzato alla risorsa.
  /users/{id}:
    get:
      tags:
        - User
      summary: Restituisce le informazioni di un utente specifico.
      parameters:
        - name: id
          in: path
          description: id dell'utente da restituire
          schema:
            type: integer
          required: true
      responses:
        200: # success
          description: Informazioni dell'evento restitutite con successo.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        400: #bad request
          description: Richiesta non valida.
        401: #unauthorized
          description: Accesso non autorizzato alla risorsa.
        404: # not found
          description: Evento non trovato.
    put:
      tags:
        - User
      summary: Aggiorna le informazioni di un utente specifico.
      description: Aggiorna i dettagli dell'utente dato il suo ID.
      parameters:
        - name: id
          in: path
          required: true
          description: ID dell'utente da aggiornare.
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user"
      responses:
        200: # success
          description: Utente aggiornato con successo.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        400: # bad request
          description: Richiesta non valida.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Dettagli sull'errore riscontrato.
                    example: Gli schemi delle risorse non coincidono.
        401: # unauthorized
          description: Accesso non autorizzato alla risorsa.
        404: # not found
          description: Utente non trovato.
    delete:
      tags:
        - User
      summary: Elimina un utente specifico.
      description: Rimuove un utente dato il suo ID.
      parameters:
        - name: id
          in: path
          required: true
          description: ID dell'utente da eliminare.
          schema:
            type: integer
      responses:
        204: # No Content
          description: Utente eliminato con successo.
        400: # bad request
          description: Richiesta non valida.
        401: # unauthorized
          description: Accesso non autorizzato alla risorsa.
        404: # not found
          description: Utente non trovato.
  /events:
    get:
      tags:
        - Event
      summary: Restituisce la lista degli eventi.
      parameters:
        - in: query
          name: startDate
          schema:
            type: string
            format: local_date
            example: "2024-08-17T14:07:30"
          required: false
        - in: query
          name: endDate
          schema:
            type: string
            format: local_date
            example: "2024-08-17T14:07:30"
          required: false
      responses:
        200: #success
          description: Risorsa JSON contenente lista di eventi.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/zone"
        400: # bad request
          description: Richiesta non valida.
        401: #unauthorized
          description: Accesso non autorizzato alla risorsa.
    post:
      tags:
        - Event
      summary: Crea un nuovo evento.
      description: Aggiunge un nuovo evento al database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/event"
      responses:
        201: # resp: evento creato
          description: Evento creato con successo.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/event"
        400: # bad request
          description: Richiesta non valida.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Descrizione dell'errore.
                    example: "Il campo 'name' è richiesto."
        401: # unauthorized
          description: Accesso non autorizzato alla risorsa.
  /events/{id}:
    get:
      tags:
        - Event
      summary: Restituisce le informazioni di un evento specifico.
      description: Ottiene i dettagli di un singolo evento dato il suo ID.
      parameters:
        - name: id
          in: path
          required: true
          description: ID dell'evento da cercare.
          schema:
            type: string
      responses:
        200:
          description: Informazioni dell'evento restituite con successo.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/event"
        400: #bad request
          description: Richiesta non valida.
        401: #unauthorized
          description: Accesso non autorizzato alla risorsa.
        404: # not found
          description: Evento non trovato.
  /zones:
    get:
      tags:
        - Zone
      summary: Restituisce la lista delle zone.
      description: Ottiene un elenco di tutte le zone disponibili.
      responses:
        200:
          description: Risorsa JSON contenente lista di zone.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/zone"
        400: #bad request
          description: Richiesta non valida.
        401: #unauthorized
          description: Accesso non autorizzato alla risorsa.
  /zones/{id}:
    get:
      tags:
        - Zone
      summary: Restituisce le informazioni di una zona specifica
      description: Ottiene i dettagli di una singola zona dato il suo ID.
      parameters:
        - name: id
          in: path
          required: true
          description: ID della zona da cercare.
          schema:
            type: string
      responses:
        200:
          description: Informazioni della zona restituite con successo.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/zone"
        400: #bad request
          description: Richiesta non valida.
        401: #unauthorized
          description: Accesso non autorizzato alla risorsa.
        404: # not found
          description: Zona non trovata.
  /auth:
    get:
      tags:
        - User
      summary: Restituisce la lista degli utenti.
      description: Restituisce la lista degli utenti presenti sulla piattaforma.
      parameters:
        - name: role
          in: query
          required: false
          description: Ruolo degli utenti da cercare, se non specificato restituisce tutti gli utenti.
          schema:
            type: string
            enum:
              - admin
              - base
      responses:
        200: # success
          description: Risorsa JSON contenente lista degli utenti.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/user"
        400: # bad request
          description: Richiesta non valida.
        401: #unauthorized
          description: Accesso non autorizzato alla risorsa.
    post:
      tags:
        - User
      summary: Crea un nuovo utente.
      description: Aggiunge un nuovo utente al database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/user"
      responses:
        201: # resp: utente creato
          description: Utente creato.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        400: # bad request
          description: Richiesta non valida.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Descrizione dell'errore.
                    example: Il campo 'name' è richiesto.
        401: # unauthorized
          description: Accesso non autorizzato alla risorsa.


components:
  schemas:
    user:
      type: object
      required:
        - id
        - name
        - surname
        - email
        - role
      properties:
        id:
          type: integer
          description: Numero identificativo dell'utente.
          example: 896544
          readOnly: true
        name:
          type: string
          description: Nome dell'utente.
          example: Mario
        surname:
          type: string
          description: Cognome dell'utente.
          example: Rossi
        email:
          type: string
          description: Email istituzionale dell'utente.
          example: mario.rossi@domain.it
        role:
          type: string
          enum:
            - admin
            - base
          description: Ruolo dell'utente nella piattaforma.
          example: admin
    event:
      type: object
      required:
        - id
        - title
        - startDate
        - endDate
        - coordinates
      properties:
        id:
          type: integer
          description: Codice identificativo evento.
          example: 10332
        title:
          type: string
          description: Titolo dell'evento registrato.
          example: "Festival dell'economia"
        startDate:
          type: string
          format: date-time
          description: Data di inizio dell'evento (oggetto data convertito in stringa).
        endDate:
          type: string
          format: date-time
          description: Data di fine dell'evento (oggetto data convertito in stringa).
        coordinates:
          type: object
          properties:
            lat:
              type: number
              description: Latitudine dell'evento (punto centrale).
              example: 46.0672
            lon:
              type: number
              description: Longitudine dell'evento (punto centrale).
              example: 11.1210
        zones:
          type: array
          description: Array di interi, sono gli id delle zone in cui l'evento ha luogo.
          items:
            type: integer
          example: [1, 2]
    zone:
      type: object
      required:
        - id
        - name
        - pivots
      properties:
        id:
          type: string
          description: Identificativo della zona.
        name:
          type: string
          description: Nome della zona.
        coordinates:
          type: array
          description: Array di coppie latitudine-longitudine per identificare i vertici del poligono rappresentante una zona.
          items:
            type: array
            items:
              type: number
            minItems: 2
            maxItems: 2
        latestData:
          type: object
          properties:
            density:
              type: number
              description: Densità registrata nella zona.
            date:
              type: string
              format: date-time
              description: Data dell'ultima rilevazione.

