openapi: 3.0.0
info:
  title: UrbanFlow API
  description: _Docs_ ufficiali per le API utilizzati nel progetto UrbanFlow.
  version: 0.0.1

servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing

# per i JWT come facciamo?
paths:
  /users:
    get:
      summary: Restituisce la lista degli utenti.
      description: Restituisce la lista degli utenti presenti sulla piattaforma
      responses:
        200: # success
          description: Risorsa JSON contenente lista degli utenti.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      example: Mario
                    surname:
                      type: string
                      example: Rossi
                    email:
                      type: string
                      format: email
                      example: mario.rossi@email.com
                    role:
                      type: string
                      enum:
                        - base
                        - admin
                      example: admin
        400: #bad request
          description: Richeista mal formata.
        401: #unautorized
          description: Accesso non autorizzato alla risorsa.      
    post:
      summary: Crea un nuovo utente.
      description: Aggiunge un nuovo utente al database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Mario
                surname:
                  type: string
                  example: Rossi
                email:
                  type: string
                  format: email
                  example: mario.rossi@email.com
                role:
                  type: string
                  enum:
                    - base
                    - admin
              required:
                - name
                - surname
                - email
                - role
      responses:
        204: # no-content
          description: Utente creato
        400: # bad request
          description: Richiesta mal formata
        401: # unauthorized
          description: Accesso non autorizzato alla risorsa. 
         
  #/users/{id}: TODO

  /events:
    get:
      summary: Restituisce la lista degli eventi
      parameters:
        - in: query
          name: startDate
          schema:
            type: string
            format: local_date
            example: '2024-08-17T14:07:30'
          required: false
        - in: query
          name: endDate
          schema:
            type: string
            format: local_date
            example: '2024-08-17T14:07:30'
          required: false

      responses:
        200: #success
          description: Risorsa JSON contenente lista di eventi.
          content:
            application/json:
              schema:
                type: object
                properties:
                  title:
                    type: string
                    example: Festival dell'economia
                  startDate:
                    type: string
                    format: date
                    example: '2024-08-17T14:07:30'
                  endDate:
                    type: string
                    format: date
                    example: '2024-08-20T14:07:30'
                  coordinates:
                    type: object
                    properties:
                      lat:
                        type: number
                        example: 46.06652452690293
                      lon: 
                        type: number
                        example: 11.122683615718385
                  zones:
                    type: array
                    items:
                      type: number
                      example: 43
                    description: Contiene gli id delle zone coinvolte nell'evento
                        
        400: # bad request
          description: Richiesta mal formata.
                
        401: #unauthorized
          description: Accesso non autorizzato alla risorsa. 
    post:
      summary: Crea un evento 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: Festival dell'economia
                startDate:
                  type: string
                  format: local_date
                  example: '2024-08-17T14:07:30'
                endDate:
                  type: string
                  format: local_date
                  example: '2024-08-20T14:07:30'
                coordinates:
                    type: object
                    properties:
                      lat:
                        type: number
                        example: 46.06652452690293
                      lon: 
                        type: number
                        example: 11.122683615718385
                zones:
                  type: array
                  items:
                    type: number
                    example: 43
                  description: Array di interi, sono gli identificativi delle zone in cui l'evento ha luogo.
           
              required:
                - name
                - startDate
                - endDate
                - coordinates
                - zones
      responses:
        204: #no content
          description: Evento inserito
        400: #bad request
          description: Richiesta mal formata
        401: #unauthorized
          description: Accesso non autorizzato alla risorsa. 

    #put TODO
    #delete TODO
  #/events/{id} TODO
  /zones:
    get:
      summary: Restituisce la lista delle zone
      description: Ottiene un elenco di tutte le zone disponibili.
      responses:
        '200':
          description:  Risorsa JSON contenente lista di zone.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: ID della zona.
                    name:
                      type: string
                      description: Nome della zona.
                    description:
                      type: string
                      description: Descrizione della zona.
                    coordinates:
                      type: object
                      properties:
                        lat:
                          type: number
                          example: 46.06652452690293
                        lon: 
                          type: number
                          example: 11.122683615718385
                      description: Coordinate della zona.
                    
                    latestData:
                      type: object
                      properties:
                        density:
                          type: number
                          description: Densità ultima misurazione
                          example: 8
                        date:
                          type: string
                          format: date
                          description: Data ultima misurazione
                          example: "2024-08-17T14:07:30"      
        '400': #bad request
          description: Richiesta mal formata
        '401': #unauthorized
          description: Accesso non autorizzato alla risorsa.
        '500': # internal server error
          description: Errore del server.
    #post TODO
    #put TODO
    #delete TODO


  /zones/{id}:
    get:
      summary: Restituisce le informazioni di una zona specifica
      description: Ottiene i dettagli di una singola zona dato il suo ID.
      parameters:
        - name: id
          in: path
          required: true
          description: ID della zona da cercare.
          schema:
            type: string
      responses:
        '200':
          description: Informazioni della zona restituite con successo.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: ID della zona.
                  name:
                    type: string
                    description: Nome della zona.
                  description:
                    type: string
                    description: Descrizione della zona.
                  coordinates:
                      type: object
                      properties:
                        lat:
                          type: number
                          example: 46.06652452690293
                        lon: 
                          type: number
                          example: 11.122683615718385
                      description: Coordinate della zona.
                  latestData:
                    type: object
                    properties:
                      density:
                        type: number
                        description: Densità ultima misurazione
                        example: 8
                      date:
                        type: string
                        format: date
                        description: Data ultima misurazione
                        example: "2024-08-17T14:07:30"
        '400': #bad request
          description: Richiesta mal formata
        '401': #unauthorized
          description: Accesso non autorizzato alla risorsa.
        '404': # not found
          description: Zona non trovata.

    


components:
  schemas:
    user:
     type: object
     properties:
      name: 
        type: string
        description: Nome dell'utente.
      surname:
        type: string
        description: Cognome dell'utente.
      email:
        type: string
        description: Email istituzionale dell'utente.
      role:
        type: string
        enum:
          - admin
          - base
        description: Ruolo dell'utente nella piattaforma.
    event:
     type: object
     properties:
      title:
        type: string
        description: Titolo dell'evento registrato.
      startDate:
        type: string
        description: Data di inizio dell'evento (oggetto data convertito in stringa).
      endDate:
        type: string
        description: Data di fine dell'evento (oggetto data convertito in stringa).
      coordinates:
        type: object
        properties:
          lat:
            type: number
            description: Latitudine dell'evento (punto centrale).
          lon:
            type: number
            description: Longitudine dell'evento (punto centrale).
      zones:
        type: array
        description: Array di interi, sono gli identificativi delle zone in cui l'evento ha luogo.
        items:
          type: integer             